### ISSUE TITLE
Some thing wrong, when route my rover fc to mavlink-udp-proxy

### ISSUE THREAD

**Issue by lida2003** [chobitsfan/mavlink-udp-proxy#3]
Hi

I have use a rover for testing. to test if it's OK to get data from FC.

1. On QGC, it's "Ready To Fly" Mode: "Hold"
2. I run the udp-proxy and get following message

```
[ INFO] [1725580434.234836624]: found MAV 1
[ INFO] [1725580434.278737811]: time offset 1725537258593911
[ INFO] [1725580434.278893269]: fc: EKF3 refusing set origin
[ INFO] [1725580434.278960310]: fc: No ap_message for mavlink id (105)
```

What might be wrong, any suggestions?

Or should I [get postion from VINS-Mono thought IPC](https://github.com/chobitsfan/mavlink-udp-proxy/issues/2) then i will be OK for setting origin?

**Comment by chobitsfan** [comment]
> fc: No ap_message for mavlink id (105)

I think HIGHRES_IMU is added recently (see https://github.com/ArduPilot/ardupilot/pull/27007)
Maybe you need to update your ardupilot version? 
P.S: I am not sure if HIGHRES_IMU is supported in rover

**Comment by lida2003** [comment]
> need to update your ardupilot version?

Yes, this PR is not merged to any of stable release yet.

4.6.0-dev works:
[ INFO] [1725763776.605588211]: found MAV 1
[ INFO] [1725763776.631456626]: time offset 1725722629593665
[ INFO] [1725763776.638772870]: fc: EKF3 IMU0 origin set
[ INFO] [1725763776.638847784]: fc: EKF3 IMU1 origin set
[ INFO] [1725763776.648151054]: fc: Field Elevation Set: 100m


But I still have question here for those two IPCs, https://github.com/chobitsfan/mavlink-udp-proxy/issues/2
